name: finance_tracker
description: "A modern Personal Finance Tracker application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts
  fl_chart: ^0.69.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  
  # UI
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
